### ISSUE TITLE
Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#80]
**Backtrace**

```
TypeError: Cannot call method 'replace' of undefined
    at removeHTML (/var/www/pepyatka/services/rss.js:91:47)
    at /var/www/pepyatka/services/rss.js:85:12
    at Array.reduce (native)
    at Function._.reduce._.foldl._.inject (/var/www/pepyatka/node_modules/underscore/underscore.js:113:28)
    at doTo (/var/www/pepyatka/services/rss.js:84:12)
    at defaultFormatter (/var/www/pepyatka/services/rss.js:101:10)
    at defaultPoster (/var/www/pepyatka/services/rss.js:105:26)
    at /var/www/pepyatka/services/rss.js:34:11
    at Array.forEach (native)
    at /var/www/pepyatka/services/rss.js:33:17
```

**Steps to reproduce**

TBD

**Snippet**

```
var defaultFormatter = function(article) {
  var removeHTML = function(article) {
    article.description = article.description.replace(/(<([^>]+)>)|(&.+;)/ig, ""); // <--- defect
    return article;
  };

  var addURL = function(article) {
    article.title = article.title + " - " + article.link;

    return article;
  };

  return doTo(article, [removeHTML, addURL]);
};
```

**Comment by epicmonkey** [comment]
too old.
