### ISSUE TITLE
Cannot read property 'userId' of null

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#81]
**Backtrace**

```
TypeError: Cannot read property 'userId' of null
    at /var/www/pepyatka/app/models/post.js:347:39
    at /var/www/pepyatka/app/models/comment.js:27:16
    at try_callback (/var/www/pepyatka/node_modules/redis/index.js:520:9)
    at RedisClient.return_reply (/var/www/pepyatka/node_modules/redis/index.js:590:13)
    at ReplyParser.<anonymous> (/var/www/pepyatka/node_modules/redis/index.js:263:14)
    at ReplyParser.EventEmitter.emit (events.js:93:17)
    at ReplyParser.send_reply (/var/www/pepyatka/node_modules/redis/lib/parser/javascript.js:297:10)
    at ReplyParser.execute (/var/www/pepyatka/node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/var/www/pepyatka/node_modules/redis/index.js:476:27)
    at Socket.<anonymous> (/var/www/pepyatka/node_modules/redis/index.js:79:14)
```

**Steps to reproduce**

TBD

**Snippet**

```
  Post.addComment = function(postId, commentId, callback) {
    models.Post.findById(postId, function(err, post) {
      post.getSubscribedTimelinesIds(function(err, timelinesIds) {
        models.Comment.findById(commentId, function(err, comment) {
          models.User.findById(comment.userId, function(err, user) { // <---- defect
            user.getRiverOfNewsId(function(err, timelineId) {
              var inRiverOfNews = timelinesIds.reduce(function (number, timelineItem){
                if (timelineItem === timelineId) number++
                return number
              }, 0);
```

**Comment by epicmonkey** [comment]
Not actual in the develop branch.
