### ISSUE TITLE
Cannot read property 'timelineIds' of null

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#82]
**Backtrace**

```
TypeError: Cannot read property 'timelineIds' of null
    at /var/www/pepyatka/app/models/timeline.js:71:38
    at /var/www/pepyatka/app/models/post.js:36:16
    at try_callback (/var/www/pepyatka/node_modules/redis/index.js:520:9)
    at RedisClient.return_reply (/var/www/pepyatka/node_modules/redis/index.js:590:13)
```

**Steps to reproduce**

TBD

***Snippet***

```
  Timeline.newPost = function(postId, additionalTimelines, callback) {
    var currentTime = new Date().getTime()

    models.Post.findById(postId, function(err, post) {
      // TODO: review this hack
      post.timelineIds = _.union(post.timelineIds, additionalTimelines) // <---- defect
      post.getSubscribedTimelinesIds(function(err, timelinesIds) {
```

**Comment by epicmonkey** [comment]
Not actual in the develop branch.
