### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#83]
**Backtrace**

```
TypeError: Cannot read property 'type' of null
    at requireAuthorization (/var/www/pepyatka/app/routes/users.js:6:16)
    at /var/www/pepyatka/app/routes/users.js:165:7
    at /var/www/pepyatka/app/models/feed-factory.js:37:13
    at /var/www/pepyatka/app/models/user.js:102:16
    at try_callback (/var/www/pepyatka/node_modules/redis/index.js:520:9)
    at RedisClient.return_reply (/var/www/pepyatka/node_modules/redis/index.js:590:13)
    at ReplyParser.<anonymous> (/var/www/pepyatka/node_modules/redis/index.js:263:14)
    at ReplyParser.EventEmitter.emit (events.js:93:17)
    at ReplyParser.send_reply (/var/www/pepyatka/node_modules/redis/lib/parser/javascript.js:297:10)
    at ReplyParser.execute (/var/www/pepyatka/node_modules/redis/lib/parser/javascript.js:211:22)
```

**Steps to reproduce**

TBD

**Snippet**

```
  var requireAuthorization = function(requestingUser, feed, callback) {
    switch(feed.type) { // <---- defect
      case 'group' :
        feed.getAdministratorsIds(function(err, administratorsIds) {
          callback(err, administratorsIds.indexOf(requestingUser.id) != -1)
        })
        break

      default :
        callback(null, requestingUser.id == feed.id)
    }
  }
```

**Comment by epicmonkey** [comment]
Not actual in the develop branch.
